### ISSUE TITLE
AWS Lambda wiki page update

### ISSUE THREAD

**Issue by vostokbike** [Foxy/foxy-shipping-endpoint-node#1]
Correction required on the wiki page regarding set up on AWS Lambda:
1. Npm package foxy-shipping-endpoint instead of foxy-shipping-response;
2. Currently, API gateway is created by default with a lambda proxy integration. It is required to switch to custom integration type in order to access body mapping template options;

**Comment by adamjudd** [comment]
@vostokbike,

Thanks for letting us know! It looks like AWS have made some improvements to working with Lambda's and API gateways. I've just reviewed the steps and updated to match their new interface.

Thanks again!
